### Strings

Single alphabetic symbols like 'a' or 'B' or '.' are called *characters*.  The empty space ' ' is also a character.  There are many more things that can be characters, but we do not need to focus on this in this class.

A sequence of characters is called a *string*.

To define a *string literal* in Python, we can use single or double quotes.

##### Example 1

In [1]:
#A string
'Hello world.'

'Hello world.'

$\Box$

Strings act a lot like lists.  We can index and slice them.  The length of a string is the number of characters (remember that the space is considered a character) in the string.  Strings can be concatenated using the '+' symbol.

##### Example 2

In [14]:
#A string
x = 'Programming is fun.'
x

'Programming is fun.'

In [23]:
x[0]

'P'

In [24]:
x[1]

'r'

In [2]:
len(x)

19

In [25]:
x[len(x)-1]

'.'

In [26]:
x[12:]

'is fun.'

In [3]:
x[0:10]

'Programmin'

In [28]:
#Another string
y = '  It is also lucrative.'
y

'  It is also lucrative.'

In [29]:
x+y

'Programming is fun.  It is also lucrative.'

In [16]:
x

'Programming is fun.'

In [17]:
y=list(x)
y

['P',
 'r',
 'o',
 'g',
 'r',
 'a',
 'm',
 'm',
 'i',
 'n',
 'g',
 ' ',
 'i',
 's',
 ' ',
 'f',
 'u',
 'n',
 '.']

In [18]:
y[0]='p'

In [19]:
string = ''
for x in y:
    string+=x
string    

'programming is fun.'

In [20]:
type(1)

int

In [21]:
str(1)

'1'

In [23]:
'variable'+str(1)

'variable1'

$\Box$

One major difference between strings and lists is that strings are *immutable* while lists are *mutable*.  This means that you cannot change a string but you can change a list.

##### Example 3

In [4]:
x[0]

'P'

In [5]:
x[0] = 'p'

TypeError: 'str' object does not support item assignment

You can define a longer string using triple quotes.

##### Example 4

In [6]:
'''This is a longer string. All work and no play makes jack is a dull boy.  jack is a good boy.  jack is a good boy.'''

'This is a longer string. All work and no play makes jack is a dull boy.  jack is a good boy.  jack is a good boy.'

$\Box$

We can use the *in* keyword to determine if a string has a character in it.

##### Example 5

In [24]:
string = 'A dog eats his meal.'

In [25]:
'o' in string

True

In [26]:
'z' in string

False

$\Box$

##### Exercise 1

Write code so that the following function performs the way that its docstring indicates.

Example: num_vowels('apple') should return 2.

num_vowels('A dog eats his meal') should return 7.

Note: For this exercise, we will assume that the only vowels are a, e, i, o, u.

In [6]:
def num_vowels(some_string):
    """
    Parameters
    -----------
    some_string: string
    
    Returns
    -----------
    The number of vowels in some_string.
    """
    count = 0
    vowels = ['a','e','i','o','u','A','E','I','O','U']
    

In [ ]:
if num_vowels('apple') != 2:
    print("Something is wrong with your code.")
elif num_vowels('aAee wwiiooww rruuxxss') != 10:
    print("Something is wrong with your code.")
else:
    print("All tests passed.")

In [42]:
some_string = 'hey you!'
for x in some_string:
    print(x)

h
e
y
 
y
o
u
!


### String Methods

There are many useful string methods that come standard with Python.  We will only cover a few here.

##### Split
The *split* string method returns a list containing all pieces of the string split up by a passed parameter.

##### Example 5

In [27]:
#A string
x = 'programming is fun and interesting.'
x

'programming is fun and interesting.'

Now, we split x using the space character.

In [28]:
x.split(' ')

['programming', 'is', 'fun', 'and', 'interesting.']

Now, we split x using the character 'a'.

In [29]:
x.split('a')

['progr', 'mming is fun ', 'nd interesting.']

We can split using a string.

In [30]:
x.split('in')

['programm', 'g is fun and ', 'terest', 'g.']

In [ ]:
['ID', 'address', 'price']

In [31]:
'ID address price'.split(' ')

['ID', 'address', 'price']

$\Box$

##### Example 6
This example illustrates the use of += with strings.

In [33]:
#A string
b = 'Some useful Data Science libraries are Numpy, Pandas, and Sci-Kit Learn.'
b

'Some useful Data Science libraries are Numpy, Pandas, and Sci-Kit Learn.'

In [34]:
c = b.split(' ')
c

['Some',
 'useful',
 'Data',
 'Science',
 'libraries',
 'are',
 'Numpy,',
 'Pandas,',
 'and',
 'Sci-Kit',
 'Learn.']

In [40]:
sentence = ''
for word in c:
    sentence+=word + ' '
sentence = sentence[0: len(sentence)-1]
sentence

'Some useful Data Science libraries are Numpy, Pandas, and Sci-Kit Learn.'

$\Box$

##### Replace
The string method *replace* replaces all occurances of one sub-string with another.

##### Example 7

In [36]:
#Recall x from above
x

'programming is fun and interesting.'

In [35]:
a = x.replace('programming', 'math')
a

'math is fun and interesting.'

Keep in mind that the original string x has not changed.  This makes sense since strings are immutable.  Thus, strings cannot be modified *in-place*.

In [39]:
x

'programming is fun and interesting.'

$\Box$


##### Lower and Upper
The *lower* and *upper* string methods convert all characters to lower or upper case.

##### Example 8

In [37]:
#recall x
x

'programming is fun and interesting.'

In [40]:
x.upper()

'PROGRAMMING IS FUN AND INTERESTING.'

$\Box$

##### Exercise 2
Write code so that the following function performs the way that its docstring indicates.

Example: ends_to_upper('programming is fun and interesting.') should return 'PROGRAMMING is fun and INTERESTING.'

In [7]:
def ends_to_upper(some_string):
    """
    Parameters
    -----------
    some_string: string
    
    Returns
    -----------
    some_string with first and last words in all caps.
    """

##### Test Your Code
Run the following code block to see if your function is working correctly.

In [ ]:
if not ends_to_upper('first second third')=='FIRST second THIRD':
    print("Something is wrong with your code.")
elif not ends_to_upper('i like math')=='I like MATH':
    print("Something is wrong with your code.")
else:
    print("All tests passed.")

##### Join

Given a string, the *join* method puts that string in between each element in a list of strings.

##### Example 9

In [9]:
#Recall c
c

['Some',
 'useful',
 'Data',
 'Science',
 'libraries',
 'are',
 'Numpy,',
 'Pandas,',
 'and',
 'Sci-Kit',
 'Learn.']

In [10]:
' '.join(c)

'Some useful Data Science libraries are Numpy, Pandas, and Sci-Kit Learn.'

In [11]:
'AAA'.join(c)

'SomeAAAusefulAAADataAAAScienceAAAlibrariesAAAareAAANumpy,AAAPandas,AAAandAAASci-KitAAALearn.'

$\Box$

### String Formatting

Consider the following string:

"Dan Smith got 90% on the Math 111 Exam."

Now, imagine how much of a pain it would be to have to retype this for every student in a Math 111 class.  The *format* string method allows us to create a string template that can be modified to take different values for student_name and score.

##### Example 10

In [12]:
#First create the template
template = "{0:s} got {1:d}% on the Math 111 Exam."

In [13]:
#Now put in Dan Smith's grade of 90%
template.format('Dan Smith', 90)

'Dan Smith got 90% on the Math 111 Exam.'

In [14]:
#Now put in Spiderman's grade of 70%.  He must have been crimefighting instead of studying
template.format('Spiderman', 70)

'Spiderman got 70% on the Math 111 Exam.'

{0:s} indicates that the 0th argument is a string.

{1:d} indicates that the 1st argument is an integer.

$\Box$

##### Example 11
{0: .1f} indicates that the 0th argument is a float rounded to one decimal place.

In [17]:
'{0: .2f} rounded to one decimal place is{1: .1f}.'.format(99.27, 99.27)

' 99.27 rounded to one decimal place is 99.3.'

In [18]:
'{0: .2f} rounded to one decimal place is{1: .1f}.'.format(55.72, 55.72)

' 55.72 rounded to one decimal place is 55.7.'

$\Box$

##### Exercise 3
Write code so that the following function performs the way that its docstring indicates.

Example: weather_report($[[$'hot',99.27$]$, $[$'cloudy', 55.72$]]$) should return 
$[$'It was hot today and the temp was 99.3 farenheight.', 'It was cloudy today and the temp was 55.7 farenheight.'$]$

In [ ]:
def weather_report(list_of_lists):
    """
    Parameters
    -----------
    list_of_lists: a list containing 2-element lists.  The 2-element lists have the form [weather_description, temperature]
    
    Returns
    -----------
    list of strings.  Each string should say 'It was weather_description today and the temp was temperature farenheight.'
    """    

In [ ]:
if not weather_report( [['hot',99.27 ], ['cloudy', 55.72 ]]) ==['It was hot today and the temp was 99.3 farenheight.', 'It was cloudy today and the temp was 55.7 farenheight.' ]:
    print("Something is wrong with your code.")
else:
    print("All tests passed.")

#### f Strings

f strings work similar to string.format.  

##### Example 12

In [1]:
x = 2
f'{x} is an integer.'

'2 is an integer.'

$\Box$

##### Example 13

In [4]:
for word in ['dog', 'cat', 'fish']:
    print(f'That animal was a {word}')

That animal was a dog
That animal was a cat
That animal was a fish


$\Box$

##### Example 14

In [5]:
for (x,y) in [(0,'a'), (1,'b'), (2,'c')]:
    print(f'{x} is a number and {y} is a letter.')

0 is a number and a is a letter.
1 is a number and b is a letter.
2 is a number and c is a letter.


$\Box$